{{ if or .Values.ssl.enabled .Values.ingress.enabled}}
{{ if not .Values.ssl.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web-cardinality.fullname" . }}-ssl
  labels:
    {{- include "web-cardinality.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ssl.tlscrt | b64enc | quote }}
  tls.key: {{ .Values.ssl.tlskey | b64enc | quote }}
{{ end }}
{{ end }}
---
{{ if or .Values.basicAuth.enabled .Values.ingress.enabled }}
{{ if not .Values.basicAuth.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web-cardinality.fullname" . }}-basic-auth
  labels:
    {{- include "web-cardinality.labels" . | nindent 4 }}
data:
  auth: {{ .Values.basicAuth.htpasswd | b64enc }}
type: Opaque
{{ end }}
{{ end }}