apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-cardinality.fullname" . }}
  labels:
    {{- include "web-cardinality.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.ssl.enabled }}
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "web-cardinality.selectorLabels" . | nindent 4 }}
