{{- if not .Values.customNginxConf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web-cardinality.fullname" . }}-config
  labels:
    {{- include "web-cardinality.labels" . | nindent 4 }}
data:   
  myserver.conf: |
       server {
          listen       80;
          server_name         myserver;
          {{- if .Values.ssl.enabled }}
          listen              443 ssl;
          ssl_certificate     /etc/nginx/ssl/tls.crt;
          ssl_certificate_key /etc/nginx/ssl/tls.key;
          {{- end }}
          {{- if .Values.basicAuth.enabled }}
          auth_basic           "Restricted content";
          auth_basic_user_file /etc/nginx/basic-auth/auth;
          {{- end }}

          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }
          
          location /healthcheck/ {
            return 200 'healthy\n';
            add_header Content-Type text/plain;
            auth_basic off;
          }
          
        }
{{- end }}