apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "web-cardinality.fullname" . }}
  labels:
    {{- include "web-cardinality.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "web-cardinality.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "web-cardinality.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "web-cardinality.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            {{- if .Values.ssl.enabled }}
            - name: https
              containerPort: 443
              protocol: TCP
            {{- end }}
          {{- if .Values.command }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          {{- end }}
          {{- if .Values.envs }}
          env:
            {{- toYaml .Values.envs | nindent 12 }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /healthcheck/
              port: http
          readinessProbe:
            httpGet:
              path: /healthcheck/
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/
            - name: static-content
              mountPath: /usr/share/nginx/html
            {{- if .Values.ssl.enabled }}
            - name: nginx-ssl
              mountPath: /etc/nginx/ssl
              readOnly: true
            {{- end }}
            {{- if .Values.basicAuth.enabled }}
            - name: nginx-basic-auth
              mountPath: /etc/nginx/basic-auth
              readOnly: true
            {{- end }}
            {{ if .Values.extraVolumeMounts}}
            {{- toYaml .Values.extraVolumeMounts | nindent 12 }}
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            {{- if .Values.customNginxConf.enabled }}
            name: "{{ .Values.customNginxConf.configMapName }}"
            {{- else }}
            name: {{ include "web-cardinality.fullname" . }}-config
            {{- end }}
        - name: static-content
          persistentVolumeClaim:
            claimName: "{{ include "web-cardinality.fullname" . }}-pvc"
        {{- if .Values.ssl.enabled }}
        - name: nginx-ssl 
          secret:
            {{ if .Values.ssl.existingSecretName }}
            secretName: nginx-ssl
            {{ else }}
            secretName: {{ include "web-cardinality.fullname" . }}-ssl
            {{ end }}
        {{- end }}
        {{- if .Values.basicAuth.enabled }}
        - name: nginx-basic-auth
          secret:
            {{ if .Values.basicAuth.existingSecretName }}
            secretName: nginx-basic-auth
            {{ else }}
            secretName: {{ include "web-cardinality.fullname" . }}-basic-auth
            {{ end }}
        {{- end }}
        {{- if .Values.extraVolumes }}
        {{- toYaml .Values.extraVolumes | nindent 8 }}
        {{- end }}
      
