{{ if .Values.persistence.createPV }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ include "web-cardinality.fullname" . }}-pv"
  labels:
    {{- include "web-cardinality.labels" . | nindent 4 }}
spec:
  capacity:
    storage: "{{ .Values.persistence.size }}"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  {{- if .Values.persistence.storageClassName }}
  storageClassName: "{{ .Values.persistence.storageClassName }}"
  {{- end }}
  hostPath:
    path: "{{ .Values.persistence.hostpath }}"
{{ end }}